apiVersion: v1
kind: Service
metadata:
  name: engine-service
  labels:
    app: engine-service
spec:
  type: ClusterIP
  selector:
    app: rune
    name: rune-engine-service-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
